[package]
name = "lemon"
version = "0.1.0"
edition = "2021"
description = "A reactive UI toolkit for Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/lucasaarch/lemon"
keywords = ["ui", "gui", "toolkit", "reactive"]
categories = ["gui"]

[dependencies]
parley = "0.9"
pollster = "0.4"
taffy = "0.7"
vello = "0.9"
wgpu = "29"
winit = "0.30"

[[example]]
name = "counter"
path = "examples/counter.rs"
