[workspace]
members = [
    "crates/lemon",
    "crates/lemon-widgets",
    "examples/counter",
    "examples/signals",
    "examples/memo",
    "examples/effects",
    "examples/keys",
    "examples/components",
    "examples/layout",
    "examples/form",
]
resolver = "2"

[workspace.package]
version = "0.2.0-alpha.7"
edition = "2021"
license = "MIT"
repository = "https://github.com/lucasaarch/lemon"

[workspace.dependencies]
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
lemon = { path = "crates/lemon", version = "0.2.0-alpha.7" }
lemon-widgets = { path = "crates/lemon-widgets", version = "0.2.0-alpha.7" }
