[package]
name = "lemon"
version.workspace = true
edition.workspace = true
description = "A reactive UI toolkit for Rust"
license.workspace = true
repository.workspace = true
keywords = ["ui", "gui", "toolkit", "reactive"]
categories = ["gui"]

[dependencies]
parley = "0.9"
pollster = "0.4"
taffy = "0.7"
vello = "0.9"
wgpu = "29"
winit = "0.30"
